(()=>{
const V='v75-growth',TOTAL=210,BASE=window.getCurriculumLessonV72,SUM=window.getCurriculumV72;
const ROLES=['Foundation','Language Builder','Listening Lab','Speaking Workshop','Reading & Writing Studio','Real-life Challenge'];
const SECTIONS={
Foundation:[['objective','เป้าหมายและสถานการณ์'],['vocab','คำศัพท์ในบริบท'],['grammar','วิธีใช้ภาษา'],['listening','ฟังภาพรวม'],['practice','ฝึกตอบแบบมีตัวช่วย'],['speaking','พูดจากข้อมูลของตนเอง'],['reading','อ่านและจับข้อมูล'],['summary','สรุปและต่อยอด']],
'Language Builder':[['objective','เป้าหมายการสื่อสาร'],['grammar','Grammar Clinic'],['practice','Pattern Lab'],['vocab','คำและวลีที่ใช้กับโครงสร้าง'],['reading','สังเกตภาษาในข้อความ'],['writing','แก้และเขียนประโยคใหม่'],['speaking','พูดโดยไม่อ่านสคริปต์'],['summary','สรุปจุดสำคัญ']],
'Listening Lab':[['objective','Listening Mission'],['vocab','Preview คำสำคัญ'],['listening','ฟังรอบแรก: จับใจความ'],['listeningDetail','ฟังรอบสอง: จับรายละเอียด'],['reading','อ่าน transcript หลังฟัง'],['speaking','พูดสรุปสิ่งที่ได้ยิน'],['writing','จดและเขียนคำตอบ'],['summary','สรุปกลยุทธ์การฟัง']],
'Speaking Workshop':[['objective','Speaking Goal'],['practice','Useful Chunks'],['listening','ฟังต้นแบบและจังหวะ'],['speaking','Shadow & Respond'],['roleplay','Role-play ตอบโต้'],['vocab','คำที่ช่วยขยายคำตอบ'],['writing','เขียน key words ก่อนพูด'],['summary','สรุปความคล่องและความชัดเจน']],
'Reading & Writing Studio':[['objective','Reading & Writing Goal'],['vocab','คำสำคัญก่อนอ่าน'],['reading','อ่านรอบแรก: จับใจความ'],['readingDetail','อ่านรอบสอง: หารายละเอียด'],['grammar','Language Notice'],['practice','วางโครงคำตอบ'],['writing','เขียนด้วยภาษาของตนเอง'],['summary','ตรวจงานและสรุป']],
'Real-life Challenge':[['objective','Mission Brief'],['reading','ข้อมูลที่ต้องใช้ตัดสินใจ'],['listening','ฟังข้อมูลเพิ่มเติม'],['mission','ตัดสินใจและเลือกภาษา'],['speaking','พูดตอบในสถานการณ์'],['writing','เขียนข้อความเพื่อจบภารกิจ'],['practice','ตรวจความชัดเจนและความสุภาพ'],['summary','Debrief: นำไปใช้จริง']]
};
const TYPES=['vocab','reverse','wordClass','listenMeaning','listenSentence','readContext','readDetail','grammar','situation','nextLine','order','gap','paraphrase','write'];
const norm=s=>String(s||'').toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}' ]+/gu,' ').replace(/\s+/g,' ').trim();
const uniq=(a,k=x=>norm(x))=>{let s=new Set;return(a||[]).filter(x=>{let q=k(x);if(!q||s.has(q))return false;s.add(q);return true})};
function shuffle(a,seed){a=[...a];let x=(seed>>>0)||1;for(let i=a.length-1;i>0;i--){x=(x*1664525+1013904223)>>>0;let j=x%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function omap(){let m=new Map;try{for(const r of(window.getOxford3000?.()||[])){let en=String(r?.word??r?.[1]??'').trim();if(en)m.set(norm(en),{en,th:String(r?.thai??r?.[4]??''),part:String(r?.part??r?.[2]??''),level:String(r?.level??r?.[3]??''),example:String(r?.example??r?.[5]??''),exampleThai:String(r?.exampleThai??r?.[6]??''),source:'core500'})}}catch{}return m}
function core(day,base){let m=omap(),c=window.getCoreVocabV73?.(day)||{newWords:[],reviewWords:[]},b=new Set(base.map(x=>norm(x.en))),out=[];for(const [status,list] of [['new',c.newWords],['review',c.reviewWords]])for(const x of(list||[])){let r=m.get(norm(x.word));if(r?.th&&!b.has(norm(r.en)))out.push({...r,status})}return out}
function support(day){let v=[],p=[],sc=[];for(let z=1;z<=14;z++)for(const d of[day-z,day+z])if(d>0&&d<=TOTAL){let b=BASE?.(d),s=SUM?.(d);if(b?.lesson){v.push(...(b.lesson.vocab||[]));p.push(...(b.lesson.examplePairs||[]))}if(s?.scenario)sc.push(s.scenario)}return{v:uniq(v,x=>norm(x.en)),p:uniq(p,x=>norm(x.en)),sc:uniq(sc)}}
function choices(c,p,seed){let out=[String(c)],seen=new Set([norm(c)]);for(const x of shuffle((p||[]).map(String).filter(Boolean),seed)){if(!seen.has(norm(x))){seen.add(norm(x));out.push(x)}if(out.length===4)break}return shuffle(out,seed+9)}
function formulas(c){return uniq([c,'Subject + V1(s/es) + ...','Subject + am/is/are + V-ing','Subject + V2 + ...','Subject + will + V1','Question word + auxiliary + subject + ...?','Subject + modal + V1']).slice(0,4)}
function quiz(day,l,test,sup){let t0=test[0]||{en:'Use English in context.',th:'ใช้ภาษาอังกฤษตามบริบท'},t1=test[1]||t0,v=l.vocab||[],v0=v[(day+2)%v.length]||{},v1=v[(day+5)%v.length]||v0,th=[...sup.v.map(x=>x.th),...v.map(x=>x.th)].filter(Boolean),en=[...sup.v.map(x=>x.en),...v.map(x=>x.en)].filter(Boolean),pth=[...sup.p.map(x=>x.th),t0.th,t1.th].filter(Boolean),pen=[...sup.p.map(x=>x.en),t0.en,t1.en].filter(Boolean),seq=shuffle(TYPES,day*7919+(l.module||0)*97).slice(0,8);
return seq.map((type,i)=>{let seed=day*101+i*13;
if(type==='vocab')return{type,mode:'choice',prompt:`“${v0.en}” หมายถึงอะไรในบทนี้?`,answer:v0.th,choices:choices(v0.th,th,seed)};
if(type==='reverse')return{type,mode:'choice',prompt:`คำอังกฤษข้อใดตรงกับ “${v1.th}”?`,answer:v1.en,choices:choices(v1.en,en,seed)};
if(type==='wordClass')return{type,mode:'choice',prompt:`คำว่า “${v1.en}” เป็นคำชนิดใด?`,answer:v1.part||'word',choices:choices(v1.part||'word',['noun','verb','adjective','adverb','preposition','pronoun','word'],seed)};
if(type==='listenMeaning')return{type,mode:'listen',prompt:'ฟังประโยคใหม่แล้วเลือกความหมาย',audio:t0.en,answer:t0.th,choices:choices(t0.th,pth,seed)};
if(type==='listenSentence')return{type,mode:'listen',prompt:'ฟังแล้วเลือกประโยคที่ได้ยิน',audio:t1.en,answer:t1.en,choices:choices(t1.en,pen,seed)};
if(type==='readContext')return{type,mode:'read',passage:`${t0.en} ${t1.en}`,prompt:'ข้อความนี้เหมาะกับสถานการณ์ใด?',answer:l.scenario,choices:choices(l.scenario,[...sup.sc,l.scenario],seed)};
if(type==='readDetail')return{type,mode:'read',passage:`${t0.en} ${t1.en}`,prompt:'ข้อใดเป็นข้อมูลที่ปรากฏในข้อความ?',answer:t1.en,choices:choices(t1.en,pen,seed)};
if(type==='grammar')return{type,mode:'choice',prompt:`โครงสร้างใดช่วยทำเป้าหมาย “${l.goal}” ได้ตรงที่สุด?`,answer:l.pattern,choices:shuffle(formulas(l.pattern),seed)};
if(type==='situation')return{type,mode:'choice',prompt:`สถานการณ์: ${l.scenario} — ประโยคใดเหมาะสมที่สุด?`,answer:t0.en,choices:choices(t0.en,pen,seed)};
if(type==='nextLine')return{type,mode:'choice',prompt:`อีกฝ่ายพูดว่า “${t0.en}” ควรตอบอย่างไรต่อ?`,answer:t1.en,choices:choices(t1.en,pen,seed)};
if(type==='order')return{type,mode:'order',prompt:'เรียงคำให้เป็นประโยคที่ถูกต้อง',tokens:shuffle(t0.en.split(/\s+/),seed),answer:t0.en};
if(type==='gap'){let w=t1.en.split(/\s+/),j=(day+i)%Math.max(1,w.length),a=w[j]||v0.en;w[j]='_____';return{type,mode:'input',prompt:`เติมคำที่หายไป: ${w.join(' ')}`,answer:a,hint:'พิมพ์เฉพาะคำที่หายไป'}}
if(type==='paraphrase')return{type,mode:'choice',prompt:`ข้อใดสื่อความหมายเดียวกับ “${t0.en}”?`,answer:t0.th,choices:choices(t0.th,pth,seed)};
return{type:'write',mode:'input',prompt:`เขียนอังกฤษให้ได้ใจความ: ${t1.th}`,answer:t1.en,hint:'เขียนเป็นประโยค ความหมายต้องครบ',flex:true};});}
function build(day){day=Math.max(1,Math.min(TOTAL,+day||1));let b=BASE?.(day)||{},s=SUM?.(day)||{},l0=b.lesson||{},role=ROLES[(day-1)%6],level=s.level||l0.v72Level||(day<=54?'A1':day<=108?'A2':day<=162?'B1':'B2'),target={A1:8,A2:10,B1:12,B2:14}[level]||10,module=Math.ceil(day/6);let vocab=uniq([...(l0.vocab||[]).map(x=>({...x,status:'topic'})),...core(day,l0.vocab||[])],x=>norm(x.en)).slice(0,target),pairs=uniq(l0.examplePairs||[],x=>norm(x.en)),teach=pairs.slice(0,4),test=pairs.slice(4,6);
for(const x of vocab){if(teach.length>=6)break;if(x.example&&x.exampleThai&&!teach.some(p=>norm(p.en)===norm(x.example))&&!test.some(p=>norm(p.en)===norm(x.example)))teach.push({en:x.example,th:x.exampleThai,source:'core500'})}
for(const x of [...vocab].reverse()){if(test.length>=4)break;if(x.example&&x.exampleThai&&!teach.some(p=>norm(p.en)===norm(x.example))&&!test.some(p=>norm(p.en)===norm(x.example)))test.push({en:x.example,th:x.exampleThai,source:'core500-test'})}
let titleBase=String(s.title||l0.v72Title||l0.title||'').replace(/^L\d+\s*·\s*/,'');let lesson={...l0,day,lessonCode:`L${day}`,module,level,role,title:`L${day} · ${titleBase}`,englishTitle:s.englishTitle||'',goal:s.goal||l0.goal||'',scenario:s.scenario||l0.scenario||'',pattern:s.grammar||l0.pattern||'',note:s.note||l0.v72Note||'',vocab,teachingPairs:teach,testPairs:test,readingText:teach.slice(0,3).map(x=>x.en).join(' '),listeningText:teach.slice(2,4).map(x=>x.en).join(' '),sections:(SECTIONS[role]||SECTIONS.Foundation).map(([kind,title],i)=>({kind,title,index:i+1}))};let q=quiz(day,lesson,test,support(day));return{version:V,lesson,grammar:{...(b.grammar||{}),formula:lesson.pattern},quiz:q,assessment:q,meta:{lessonCode:`L${day}`,module,role,level,vocabCount:vocab.length,newWordCount:vocab.filter(x=>x.status==='new').length,reviewWordCount:vocab.filter(x=>x.status==='review').length,assessmentSignature:q.map(x=>x.type).join('>'),teachTestSeparated:true}}}
window.getCurriculumLessonV75=build;window.getCurriculumLessonV72=build;window.CURRICULUM_V75={version:V,totalLessons:TOTAL,roles:ROLES,assessmentTypes:TYPES,vocabTargets:{A1:8,A2:10,B1:12,B2:14}};
window.auditCurriculumV75=()=>{let sig=new Set,bad=[];for(let d=1;d<=TOTAL;d++){let x=build(d);sig.add(x.meta.assessmentSignature);if(x.quiz.length!==8||x.lesson.sections.length!==8||x.lesson.vocab.length<8||x.lesson.testPairs.some(t=>x.lesson.teachingPairs.some(p=>norm(p.en)===norm(t.en))))bad.push(d)}return{version:V,totalLessons:TOTAL,distinctAssessmentSignatures:sig.size,badLessons:bad,ok:!bad.length&&sig.size>=12}};
})();