(()=>{
  const todayKey=()=>new Date().toLocaleDateString('en-CA');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const pick=(a,n=1)=>n===1?shuffle(a)[0]:shuffle(a).slice(0,n);
  const BANK=[
    ['water','น้ำ','I need some water.','ฉันต้องการน้ำ'],['coffee','กาแฟ','I would like a coffee, please.','ฉันขอกาแฟหนึ่งแก้ว'],['food','อาหาร','The food is very good.','อาหารอร่อยมาก'],['work','งาน / ทำงาน','I work every day.','ฉันทำงานทุกวัน'],['home','บ้าน','I am at home now.','ตอนนี้ฉันอยู่บ้าน'],['help','ช่วย / ความช่วยเหลือ','Can you help me, please?','ช่วยฉันหน่อยได้ไหม'],['time','เวลา','What time is it?','ตอนนี้กี่โมง'],['today','วันนี้','I am busy today.','วันนี้ฉันยุ่ง'],['tomorrow','พรุ่งนี้','I will call you tomorrow.','ฉันจะโทรหาคุณพรุ่งนี้'],['yesterday','เมื่อวาน','I worked yesterday.','เมื่อวานฉันทำงาน'],
    ['station','สถานี','Where is the station?','สถานีอยู่ที่ไหน'],['airport','สนามบิน','The airport is very busy.','สนามบินยุ่งมาก'],['hotel','โรงแรม','I have a hotel reservation.','ฉันจองโรงแรมไว้แล้ว'],['room','ห้อง','Where is my room?','ห้องของฉันอยู่ที่ไหน'],['ticket','ตั๋ว','I need two tickets.','ฉันต้องการตั๋วสองใบ'],['train','รถไฟ','I take the train to work.','ฉันนั่งรถไฟไปทำงาน'],['bus','รถบัส','The bus is late.','รถบัสมาสาย'],['taxi','แท็กซี่','Where can I get a taxi?','ฉันขึ้นแท็กซี่ได้ที่ไหน'],['gate','เกต / ประตูขึ้นเครื่อง','Where is gate twelve?','เกตสิบสองอยู่ที่ไหน'],['bag','กระเป๋า','My bag is missing.','กระเป๋าของฉันหาย'],
    ['price','ราคา','What is the price?','ราคาเท่าไร'],['cheap','ราคาถูก','This shirt is cheap.','เสื้อตัวนี้ราคาถูก'],['expensive','แพง','This hotel is expensive.','โรงแรมนี้แพง'],['large','ใหญ่','Do you have a larger size?','มีไซซ์ใหญ่กว่านี้ไหม'],['small','เล็ก','I need a small bag.','ฉันต้องการกระเป๋าใบเล็ก'],['card','บัตร','Can I pay by card?','ฉันจ่ายด้วยบัตรได้ไหม'],['cash','เงินสด','I only have cash.','ฉันมีแต่เงินสด'],['buy','ซื้อ','I want to buy this.','ฉันต้องการซื้ออันนี้'],['open','เปิด','The shop is open.','ร้านเปิดอยู่'],['closed','ปิด','The bank is closed.','ธนาคารปิดแล้ว'],
    ['family','ครอบครัว','I live with my family.','ฉันอยู่กับครอบครัว'],['friend','เพื่อน','She is my friend.','เธอเป็นเพื่อนของฉัน'],['name','ชื่อ','What is your name?','คุณชื่ออะไร'],['phone','โทรศัพท์','My phone is new.','โทรศัพท์ของฉันใหม่'],['email','อีเมล','Please send me an email.','กรุณาส่งอีเมลให้ฉัน'],['meeting','ประชุม','I have a meeting at ten.','ฉันมีประชุมตอนสิบโมง'],['project','โครงการ','I am working on a project.','ฉันกำลังทำโครงการ'],['problem','ปัญหา','There is a problem.','มีปัญหา'],['ready','พร้อม','I am ready now.','ตอนนี้ฉันพร้อมแล้ว'],['busy','ยุ่ง','I am busy this morning.','เช้านี้ฉันยุ่ง'],
    ['happy','มีความสุข','I am happy today.','วันนี้ฉันมีความสุข'],['tired','เหนื่อย','I feel tired.','ฉันรู้สึกเหนื่อย'],['hungry','หิว','I am hungry.','ฉันหิว'],['sorry','ขอโทษ','I am sorry.','ฉันขอโทษ'],['please','กรุณา','Please wait here.','กรุณารอที่นี่'],['thanks','ขอบคุณ','Thanks for your help.','ขอบคุณสำหรับความช่วยเหลือ'],['where','ที่ไหน','Where is the bathroom?','ห้องน้ำอยู่ที่ไหน'],['when','เมื่อไร','When do you start work?','คุณเริ่มงานเมื่อไร'],['why','ทำไม','Why are you late?','ทำไมคุณมาสาย'],['because','เพราะว่า','I am tired because I worked late.','ฉันเหนื่อยเพราะทำงานดึก'],
    ['morning','ตอนเช้า','I drink coffee in the morning.','ฉันดื่มกาแฟตอนเช้า'],['night','กลางคืน','I work at night.','ฉันทำงานกลางคืน'],['left','ซ้าย','Turn left here.','เลี้ยวซ้ายตรงนี้'],['right','ขวา','Turn right at the corner.','เลี้ยวขวาที่หัวมุม'],['straight','ตรงไป','Go straight for two minutes.','ตรงไปสองนาที'],['near','ใกล้','The station is near the hotel.','สถานีอยู่ใกล้โรงแรม'],['far','ไกล','The airport is far from here.','สนามบินอยู่ไกลจากที่นี่'],['wait','รอ','Please wait a moment.','กรุณารอสักครู่'],['understand','เข้าใจ','I understand now.','ตอนนี้ฉันเข้าใจแล้ว'],['again','อีกครั้ง','Could you say that again?','ช่วยพูดอีกครั้งได้ไหม']
  ].map((x,id)=>({id,en:x[0],th:x[1],sentence:x[2],sentenceTh:x[3]}));
  const DIALOGS=[
    ['พนักงานถาม “What would you like to drink?”',['I would like a coffee, please.','I am a station.','Turn left coffee.'],0],
    ['คุณอยากถามว่าห้องน้ำอยู่ไหน',['Where is the bathroom?','How much bathroom?','I like bathroom.'],0],
    ['เจ้าหน้าที่บอกให้รอสักครู่',['Okay, thank you.','No station.','Price please left.'],0],
    ['คุณมีการจองโรงแรมแล้ว',['I have a reservation.','I have a gate.','I am reservation.'],0],
    ['คุณอยากจ่ายด้วยบัตร',['Can I pay by card?','Can I eat the card?','Where is card time?'],0],
    ['คุณฟังไม่ทันและอยากให้พูดซ้ำ',['Could you say that again?','Could you close again?','How much say?'],0],
    ['คุณอยากบอกว่ากระเป๋าหาย',['My bag is missing.','My bag is delicious.','My bag is a hotel.'],0],
    ['คุณอยากขอความช่วยเหลือ',['Can you help me, please?','Can you price me?','Help is gate twelve.'],0],
    ['คุณต้องการตั๋วสองใบ',['Two tickets, please.','Two coffees station.','Please two hotel.'],0],
    ['คุณอยากถามราคาเสื้อ',['How much is this shirt?','Where time is shirt?','Who is this price?'],0]
  ];
  const META={match:['🧩','Word Match'],builder:['🧱','Sentence Builder'],listen:['🎧','Listening Hunt'],sprint:['⚡','Flash Sprint'],rush:['🏃','Meaning Rush'],gap:['🔤','Missing Word'],translate:['🇹🇭','Thai → English'],memory:['🧠','Memory Flip'],dialog:['🗣️','Survival Dialog'],spell:['👂','Spell by Ear'],trap:['🎭','True or Trap']};
  const QUESTS=[['learn','📚 จำคำใหม่',3,'คำ'],['quiz','🎯 ตอบ Quiz ถูก',3,'ข้อ'],['ai','✨ คุยกับ AI Coach',1,'ครั้ง'],['game','🎮 จบ Mini Game',1,'เกม'],['listen','🎧 Listening ถูก',2,'ข้อ']];
  const qmap=Object.fromEntries(QUESTS.map(x=>[x[0],x]));
  const fresh=()=>{const seed=Number(todayKey().replaceAll('-',''));const ids=QUESTS.map(x=>x[0]);return{date:todayKey(),progress:{learn:0,quiz:0,ai:0,game:0,listen:0},rewarded:{},combo:0,bestCombo:0,stars:0,dailyQuestIds:[ids[seed%5],ids[(seed+2)%5],ids[(seed+4)%5]],aiMission:null,recent:[]}};
  function lab(){if(!state.gameLab||state.gameLab.date!==todayKey())state.gameLab=fresh();return state.gameLab}
  function persist(){try{saveState()}catch{}}
  function addProgress(id,n=1){const l=lab();l.progress[id]=(l.progress[id]||0)+n;const q=qmap[id];if(q&&l.progress[id]>=q[2]&&!l.rewarded[id]){l.rewarded[id]=true;l.stars=(l.stars||0)+1;state.xp=(Number(state.xp)||0)+15;toast('⭐ Quest สำเร็จ +15 XP')}if((l.dailyQuestIds||[]).every(k=>(l.progress[k]||0)>=(qmap[k]?.[2]||1))&&!l.rewarded.all){l.rewarded.all=true;l.stars=(l.stars||0)+2;state.xp=(Number(state.xp)||0)+30;toast('🏆 Daily Quest ครบ +30 XP')}persist()}
  function correct(xp,label){state.xp=(Number(state.xp)||0)+xp;const l=lab();l.combo=(l.combo||0)+1;l.bestCombo=Math.max(l.bestCombo||0,l.combo);persist();toast(`+${xp} XP · ${label}`)}
  function miss(){lab().combo=0;persist()}
  function toast(text){let e=document.querySelector('#gameLabToast');if(!e){e=document.createElement('div');e.id='gameLabToast';e.className='game-toast';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1400)}
  function close(){const d=document.querySelector('#gameLabModal');if(!d)return;try{if(d.open)d.close()}catch{}d.remove()}
  function modal(title,body){close();const d=document.createElement('dialog');d.id='gameLabModal';d.className='game-dialog';d.innerHTML=`<section class="game-panel"><header class="game-panel-head"><h2>${esc(title)}</h2><button class="game-close" type="button" aria-label="ปิด">×</button></header><div id="gameLabBody">${body}</div></section>`;document.body.appendChild(d);d.querySelector('.game-close').addEventListener('click',close);d.addEventListener('cancel',e=>{e.preventDefault();close()});d.addEventListener('click',e=>{if(e.target===d)close()});if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');return d}
  function finish(type,title,score,total){addProgress('game');const d=document.querySelector('#gameLabModal');if(!d)return;d.querySelector('#gameLabBody').innerHTML=`<div class="game-finish"><div>🎉</div><h2>${esc(title)}</h2><p>ทำได้ ${score}/${total} · บันทึก XP และ Quest แล้ว</p><div class="game-finish-actions"><button class="lab-primary" data-again="${type}">▶ เล่นเกมนี้อีก</button><button class="lab-secondary" data-random>🎲 สุ่มเกมอื่น</button><button class="lab-secondary" data-close>✕ ปิด</button></div></div>`}
  function nonRepeat(n=1){const l=lab(),recent=new Set((l.recent||[]).slice(-18));let pool=BANK.filter(x=>!recent.has(x.id));if(pool.length<n)pool=BANK;const a=pick(pool,n);const arr=Array.isArray(a)?a:[a];l.recent=[...(l.recent||[]),...arr.map(x=>x.id)].slice(-30);persist();return n===1?arr[0]:arr}
  function hub(){const l=lab();const qs=(l.dailyQuestIds||[]).map(id=>qmap[id]).filter(Boolean);const cards=[['mission','✨','AI Surprise Mission','ภารกิจ AI รายวัน'],['mix','🎲','Daily Mix','สุ่มเกมที่ไม่ใช่เกมล่าสุด'],...Object.entries(META).map(([id,m])=>[id,m[0],m[1],id==='dialog'?'ฝึกสถานการณ์จริง':'โจทย์สุ่มจากคลังคำขนาดใหญ่'])];return `<section class="quest-hub"><div class="quest-head"><div><small>DAILY QUEST</small><h2>ภารกิจวันนี้</h2></div><b>⭐ ${l.stars||0} · ⚡ ${l.combo||0}</b></div><div class="quest-list">${qs.map(q=>{const p=Math.min(l.progress[q[0]]||0,q[2]);return `<div class="quest-item ${p>=q[2]?'done':''}"><b>${p>=q[2]?'✅':q[1]}</b><span>${p}/${q[2]} ${q[3]}</span></div>`}).join('')}</div></section><div class="game-title"><div><small>GAME LAB V31</small><h2>🎮 เลือกเกมฝึก</h2></div><span>13 โหมด · ลดการวนซ้ำ</span></div><section class="game-grid">${cards.map((c,i)=>`<button class="game-card ${i<2?'featured':''}" type="button" data-game="${c[0]}"><div class="game-icon">${c[1]}</div><h3>${esc(c[2])}</h3><p>${esc(c[3])}</p></button>`).join('')}</section>`}
  function enhance(){if(typeof view==='undefined'||view!=='home')return;const app=document.querySelector('#app');if(!app||app.querySelector('[data-game-lab-v31]'))return;const hero=app.querySelector('.hero');if(!hero)return;const wrap=document.createElement('div');wrap.dataset.gameLabV31='1';wrap.innerHTML=hub();hero.after(wrap)}
  function match(){const set=nonRepeat(4),left=pick(set,4),right=pick(set,4);let selected='',score=0;const d=modal('🧩 Word Match',`<p class="game-sub">เลือกคำอังกฤษ แล้วเลือกความหมายไทยให้ครบ</p><div class="match-board"><div>${left.map(x=>`<button class="word-tile" data-en="${x.id}">${esc(x.en)}</button>`).join('')}</div><div>${right.map(x=>`<button class="word-tile" data-th="${x.id}">${esc(x.th)}</button>`).join('')}</div></div>`);d.querySelectorAll('[data-en]').forEach(b=>b.onclick=()=>{d.querySelectorAll('[data-en]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.en});d.querySelectorAll('[data-th]').forEach(b=>b.onclick=()=>{if(!selected)return;if(b.dataset.th===selected){d.querySelectorAll(`[data-en="${selected}"],[data-th="${selected}"]`).forEach(x=>{x.disabled=true;x.classList.add('correct')});score++;correct(4,'จับคู่ถูก');selected='';if(score===4)setTimeout(()=>finish('match','จับคู่ครบแล้ว',score,4),350)}else{b.classList.add('wrong');miss();setTimeout(()=>b.classList.remove('wrong'),350)}})}
  function builder(){const w=nonRepeat();const target=w.sentence.replace(/[.!?]$/,'');const tokens=target.split(/\s+/);let chosen=[];const d=modal('🧱 Sentence Builder',`<p class="game-prompt">${esc(w.sentenceTh)}</p><div id="answer" class="builder-answer"></div><div id="pool" class="builder-pool">${shuffle(tokens).map((t,i)=>`<button class="token-btn" data-token="${esc(t)}" data-i="${i}">${esc(t)}</button>`).join('')}</div><div class="lab-actions"><button class="lab-secondary" id="reset">เริ่มใหม่</button><button class="lab-primary" id="check">ตรวจคำตอบ</button></div>`);const draw=()=>{d.querySelector('#answer').textContent=chosen.join(' ')};d.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{if(b.disabled)return;b.disabled=true;chosen.push(b.dataset.token);draw()});d.querySelector('#reset').onclick=()=>{chosen=[];d.querySelectorAll('[data-token]').forEach(b=>b.disabled=false);draw()};d.querySelector('#check').onclick=()=>{if(chosen.join(' ').toLowerCase()===target.toLowerCase()){correct(12,'เรียงประโยค');finish('builder','สร้างประโยคสำเร็จ',1,1)}else{miss();toast('ยังไม่ถูก ลองเรียงใหม่')}}}
  function choicesGame(type,title,prompt,answer,choices,onCorrect=()=>{}){const d=modal(title,`<p class="game-prompt">${esc(prompt)}</p><div class="choice-stack">${shuffle(choices).map(c=>`<button class="lab-choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div>`);d.querySelectorAll('.lab-choice').forEach(b=>b.onclick=()=>{d.querySelectorAll('.lab-choice').forEach(x=>x.disabled=true);if(b.dataset.value===answer){b.classList.add('correct');correct(5,title);onCorrect();setTimeout(()=>finish(type,'ตอบถูก',1,1),350)}else{b.classList.add('wrong');miss();toast(`คำตอบ: ${answer}`);setTimeout(()=>finish(type,'จบรอบ',0,1),550)}})}
  function listen(){const w=nonRepeat(),wrong=nonRepeat(3).filter(x=>x.id!==w.id).map(x=>x.th);const d=modal('🎧 Listening Hunt',`<button class="listen-orb" id="play">🔊</button><p class="game-sub">ฟังแล้วเลือกความหมาย</p><div class="choice-stack">${shuffle([w.th,...wrong]).slice(0,4).map(x=>`<button class="lab-choice" data-v="${esc(x)}">${esc(x)}</button>`).join('')}</div>`);const say=()=>{try{speak(w.en)}catch{}};d.querySelector('#play').onclick=say;setTimeout(say,120);d.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{if(b.dataset.v===w.th){b.classList.add('correct');correct(6,'ฟังถูก');addProgress('listen');setTimeout(()=>finish('listen','Listening สำเร็จ',1,1),300)}else{b.classList.add('wrong');miss();toast(`คำตอบ: ${w.th}`)}})}
  function sprint(){const qs=nonRepeat(5);let i=0,score=0;const d=modal('⚡ Flash Sprint','<div id="stage"></div>');const next=()=>{if(i>=qs.length)return finish('sprint','Sprint จบแล้ว',score,qs.length);const w=qs[i],wrong=pick(BANK.filter(x=>x.id!==w.id),2);d.querySelector('#stage').innerHTML=`<div class="game-progress">${i+1}/5</div><p class="game-prompt">${esc(w.en)}</p><div class="choice-stack">${shuffle([w,...wrong]).map(x=>`<button class="lab-choice" data-id="${x.id}">${esc(x.th)}</button>`).join('')}</div>`;d.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.id)===w.id){score++;correct(3,'Flash')}else miss();i++;setTimeout(next,250)})};next()}
  function rush(){const w=nonRepeat(),wrong=pick(BANK.filter(x=>x.id!==w.id),3);choicesGame('rush','🏃 Meaning Rush',w.en,w.th,[w,...wrong].map(x=>x.th))}
  function gap(){const w=nonRepeat(),parts=w.sentence.replace(/[.!?]$/,'').split(/\s+/);let idx=parts.findIndex(x=>x.toLowerCase().includes(w.en.toLowerCase().split(' ')[0]));if(idx<0)idx=Math.floor(parts.length/2);const ans=parts[idx],display=parts.map((x,i)=>i===idx?'_____':x).join(' '),wrong=pick(BANK.filter(x=>x.en!==ans.toLowerCase()),3).map(x=>x.en);choicesGame('gap','🔤 Missing Word',display,ans,[ans,...wrong])}
  function translate(){const w=nonRepeat(),wrong=pick(BANK.filter(x=>x.id!==w.id),3).map(x=>x.sentence);choicesGame('translate','🇹🇭 Thai → English',w.sentenceTh,w.sentence,[w.sentence,...wrong])}
  function survival(){const q=pick(DIALOGS);choicesGame('dialog','🗣️ Survival Dialog',q[0],q[1][q[2]],q[1])}
  function spell(){const w=nonRepeat();const d=modal('👂 Spell by Ear',`<button class="listen-orb" id="play">🔊</button><p class="game-sub">ฟังแล้วพิมพ์คำศัพท์</p><input class="spell-input" id="spell" autocomplete="off" autocapitalize="none"><button class="lab-primary full" id="check">ตรวจคำตอบ</button>`);const say=()=>{try{speak(w.en)}catch{}};d.querySelector('#play').onclick=say;setTimeout(say,120);d.querySelector('#check').onclick=()=>{const ok=d.querySelector('#spell').value.trim().toLowerCase()===w.en.toLowerCase();if(ok){correct(8,'Spell');finish('spell','สะกดถูก',1,1)}else{miss();toast(`คำตอบ: ${w.en}`)}}}
  function trap(){const w=nonRepeat(),truth=Math.random()>.5,shown=truth?w.th:pick(BANK.filter(x=>x.id!==w.id)).th;const d=modal('🎭 True or Trap',`<p class="game-prompt center">${esc(w.en)}</p><p class="trap-meaning">${esc(shown)}</p><div class="trap-actions"><button class="lab-primary" data-bool="1">✓ จริง</button><button class="lab-secondary" data-bool="0">✕ หลอก</button></div>`);d.querySelectorAll('[data-bool]').forEach(b=>b.onclick=()=>{const ok=(b.dataset.bool==='1')===truth;if(ok){correct(5,'True or Trap');finish('trap','ตัดสินถูก',1,1)}else{miss();finish('trap','รอบนี้พลาด',0,1)}})}
  function memory(){const set=nonRepeat(4),cards=shuffle(set.flatMap(w=>[{k:w.id,t:w.en},{k:w.id,t:w.th}]));let first=null,lock=false,pairs=0;const d=modal('🧠 Memory Flip',`<div class="memory-grid">${cards.map((c,i)=>`<button class="memory-card" data-i="${i}" data-k="${c.k}"><span>?</span><b>${esc(c.t)}</b></button>`).join('')}</div>`);d.querySelectorAll('.memory-card').forEach(b=>b.onclick=()=>{if(lock||b.classList.contains('matched')||b===first)return;b.classList.add('open');if(!first){first=b;return}if(first.dataset.k===b.dataset.k){first.classList.add('matched');b.classList.add('matched');first=null;pairs++;correct(4,'Memory');if(pairs===4)setTimeout(()=>finish('memory','จับคู่ครบ',4,4),350)}else{lock=true;miss();setTimeout(()=>{first.classList.remove('open');b.classList.remove('open');first=null;lock=false},650)}})}
  async function mission(){const d=modal('✨ AI Surprise Mission',`<div class="mission-card"><small>TODAY'S AI SURPRISE</small><h3>กำลังสร้างภารกิจ...</h3><p>ถ้า AI ไม่พร้อม ระบบจะใช้ภารกิจสำรองให้ทันที</p></div>`);let data;try{const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),9000);const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},signal:ctrl.signal,body:JSON.stringify({mode:'mission',level:Math.max(1,Math.floor((state.xp||0)/100)+1),name:state.name,scenario:state.scenario,message:'Create one short English mission'})});clearTimeout(t);if(!r.ok)throw 0;data=await r.json()}catch{data={text:'Say three sentences about your day.',thai:'พูด 3 ประโยคสั้น ๆ เกี่ยวกับวันนี้'}}if(!document.body.contains(d))return;lab().aiMission={date:todayKey(),text:String(data.text||'Say three sentences about your day.'),thai:String(data.thai||'พูด 3 ประโยคสั้น ๆ เกี่ยวกับวันนี้')};persist();d.querySelector('#gameLabBody').innerHTML=`<div class="mission-card"><small>TODAY'S AI SURPRISE</small><h3>${esc(lab().aiMission.text)}</h3><p>${esc(lab().aiMission.thai)}</p><div class="mission-reward">🎁 ทำภารกิจแล้วไปคุยต่อใน AI Coach +15 XP</div><div class="lab-actions"><button class="lab-secondary" data-close>ไว้ทีหลัง</button><button class="lab-primary" id="missionGo">ไปทำภารกิจ</button></div></div>`;d.querySelector('[data-close]').onclick=close;d.querySelector('#missionGo').onclick=()=>{state.xp=(Number(state.xp)||0)+15;persist();close();const enter=window.__aiCoreV31?.enter;if(enter)enter({mission:lab().aiMission});else if(typeof go==='function')go('ai')}}
  function open(type){if(type==='mix'){const ids=Object.keys(META),last=lab().lastGame;type=pick(ids.filter(x=>x!==last))}lab().lastGame=type;persist();({match,builder,listen,sprint,rush,gap,translate,memory,dialog:survival,spell,trap,mission}[type]||rush)()}
  document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;const card=t.closest('[data-game]');if(card){e.preventDefault();open(card.dataset.game);return}const again=t.closest('[data-again]');if(again){e.preventDefault();open(again.dataset.again);return}if(t.closest('[data-random]')){e.preventDefault();open('mix');return}if(t.closest('[data-close]')){e.preventDefault();close()}});
  try{const r0=render;render=function(){r0();requestAnimationFrame(enhance)}}catch{}
  try{const m0=markWord;markWord=function(ok){if(ok)addProgress('learn');return m0(ok)}}catch{}
  try{const a0=answerQuestion;answerQuestion=function(btn){try{const q=quiz[quizIndex];if(Number(btn.dataset.choice)===q.a)addProgress('quiz')}catch{}return a0(btn)}}catch{}
  requestAnimationFrame(enhance);
  window.__gameLabV31={open,close,addProgress,version:'31'};
})();