(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ROUTES={
    starter:{cefr:'Pre-A1 / A1',start:'L0',path:'L0 → L1 → L2 → L3 → L4 → L5',focus:'เริ่มจากประโยคพื้นฐาน แล้วค่อยต่อยอดสู่สถานการณ์จริงและการสนทนาต่อเนื่อง'},
    basic:{cefr:'A1–A2',start:'L1',path:'L1 → L2 → L3 → L4 → L5',focus:'เริ่มจากภาษาในชีวิตประจำวัน ต่อด้วยการสร้างประโยค สถานการณ์จริง และการสนทนา'},
    intermediate:{cefr:'A2–B1',start:'L2',path:'L2 → L3 → L4 → L5',focus:'เริ่มจากการสร้างประโยค อดีต/อนาคต ต่อด้วยสถานการณ์จริง การเล่าเรื่อง และการสนทนาต่อเนื่อง'},
    upper:{cefr:'B1–B2',start:'L4',path:'L4 → L5',focus:'เน้นอธิบายเหตุผล แสดงความคิดเห็น แก้สถานการณ์ เล่าเรื่อง และสื่อสารต่อเนื่องอย่างเป็นธรรมชาติ'}
  };
  function route(){let id='starter';try{id=window.getLearnerLevel?.()||'starter'}catch{}return ROUTES[id]||ROUTES.starter}
  function cardHtml(){const r=route();return `<section class="learning-guide-card" id="learningGuideCard"><div class="learning-guide-head"><div><div class="learning-guide-kicker">START HERE · คู่มือสำหรับผู้เรียน</div><h2>👋 เรียนตามระดับของคุณจนสื่อสารได้</h2><p>ระดับ ${esc(r.cefr)} · ${esc(r.focus)} โดยไม่รีเซ็ตบทที่เคยเรียน</p></div><button class="learning-guide-open" id="learningGuideOpen" type="button">เปิดคู่มือเริ่มเรียน</button></div><div class="learning-guide-route"><span>1 · Roadmap</span><span>2 · Oxford 3000</span><span>3 · Review</span><span>4 · Quiz / Game</span><span>5 · เขียน</span><span>6 · Sentence Coach</span></div></section>`}
  function modalHtml(){const r=route();return `<div class="learning-guide-overlay" id="learningGuideModal"><section class="learning-guide-panel" role="dialog" aria-modal="true" aria-label="คู่มือเริ่มเรียน"><div class="learning-guide-panel-head"><div><h2>📘 แผนเรียนระดับ ${esc(r.cefr)}</h2><p>เส้นทางของคุณ: <b>${esc(r.path)}</b> · เป้าหมายคือสื่อสารต่อเนื่องระดับกลางถึงสูง</p></div><button class="learning-guide-close" id="learningGuideClose" type="button">ปิด</button></div>
  <div class="learning-guide-today">
    <div class="guide-step"><div class="guide-step-num">1</div><div><b>เริ่มที่ ${esc(r.start)} ตามระดับของคุณ</b><span>${esc(r.focus)} บทก่อนระดับยังเปิดทบทวนได้ แต่ไม่บังคับให้เริ่มใหม่</span></div></div>
    <div class="guide-step"><div class="guide-step-num">2</div><div><b>Oxford 3000 ตาม CEFR</b><span>เรียนคำศัพท์ที่เหมาะกับระดับ ดูความหมาย ฟังเสียง พูดตาม และอ่านตัวอย่างประโยค</span></div></div>
    <div class="guide-step"><div class="guide-step-num">3</div><div><b>ทบทวนคำที่ยังไม่แม่น</b><span>เน้นคำที่เคยตอบผิดหรือยังจำไม่ได้ก่อนเพิ่มคำใหม่มากเกินไป</span></div></div>
    <div class="guide-step"><div class="guide-step-num">4</div><div><b>Quiz หรือ Game ตามระดับ</b><span>Word Match, Listening, Sentence Builder และเกมอื่นจะใช้คำและประโยคตามระดับที่เลือก</span></div></div>
    <div class="guide-step"><div class="guide-step-num">5</div><div><b>เขียนภาษาอังกฤษ 2–5 ประโยค</b><span>ใช้ Pattern และคำศัพท์ของระดับปัจจุบัน เขียนเรื่องงาน ชีวิตประจำวัน แผน ความคิดเห็น หรือสถานการณ์จริง</span></div></div>
    <div class="guide-step"><div class="guide-step-num">6</div><div><b>จบด้วย Sentence Coach 5–10 นาที</b><span>แต่งประโยคเอง ตรวจคำตอบ อ่านเหตุผลเมื่อผิด แล้วแก้จนสามารถสร้างประโยคได้ด้วยตัวเอง</span></div></div>
  </div>
  <div class="guide-section"><h3>⏱️ เวลาเรียนที่แนะนำ 30–45 นาที/วัน</h3><div class="guide-time"><div><b>10–15 นาที</b><span>Roadmap</span></div><div><b>10–15 นาที</b><span>Oxford 3000</span></div><div><b>5–10 นาที</b><span>Review / Quiz / Game</span></div><div><b>5–10 นาที</b><span>Sentence Coach</span></div></div><div class="guide-note">ระดับที่เลือกเป็นจุดเริ่ม ไม่ใช่การลบบทเดิม ผู้เรียนสามารถย้อนทบทวนระดับก่อนหน้าได้ตลอด</div></div>
  <div class="guide-section"><h3>📈 วิธีพัฒนาไปจนสื่อสารระดับกลาง–สูง</h3><div class="guide-week"><div><b>ช่วงที่ 1:</b> ทำ Pattern และประโยคหลักของระดับปัจจุบันให้คล่อง</div><div><b>ช่วงที่ 2:</b> ใช้คำศัพท์ในประโยคจริง ผ่าน Quiz, Listening และ Game</div><div><b>ช่วงที่ 3:</b> ฝึกสถานการณ์จริง เช่น ร้านอาหาร เดินทาง โรงแรม งาน และการแก้ปัญหา</div><div><b>ช่วงที่ 4:</b> ฝึกถามต่อ แสดงความคิดเห็น อธิบายเหตุผล เปรียบเทียบ และเล่าเรื่อง</div><div><b>ช่วงที่ 5:</b> ทำ L5 เพื่อสื่อสารต่อเนื่อง 5–10 นาทีในหัวข้อคุ้นเคยและสถานการณ์จริง</div></div></div>
  <div class="guide-section"><h3>✅ เมื่อไรควรไปบทถัดไป</h3><ol class="guide-pass"><li>เข้าใจ Pattern และความหมายหลัก</li><li>แต่งประโยคของตัวเองได้อย่างน้อย 2–3 ประโยค</li><li>ฟังประโยคสั้นแล้วจับใจความได้</li><li>ทำ Sentence Coach และแก้ประโยคที่ผิดได้</li><li>Quiz / Review / Game ได้ประมาณ 80% หรือรู้ว่าจุดที่ผิดคืออะไร</li></ol><div class="guide-note">เป้าหมายหลักคือ “ฟังเข้าใจ → สร้างประโยค → พูดสื่อสาร → อ่านและเขียนได้” ไม่ใช่สะสม XP อย่างเดียว</div></div>
  <div class="guide-actions"><button class="guide-primary" id="guideGoRoadmap" type="button">1 · ไป Learning Roadmap</button><button class="guide-secondary" id="guideGoCore" type="button">2 · เรียน Oxford 3000</button><button class="guide-secondary" id="guideGoReview" type="button">3 · ไปทบทวน</button><button class="guide-secondary" id="guideGoSentence" type="button">6 · ไป Sentence Coach</button></div></section></div>`}
  function closeModal(){document.querySelector('#learningGuideModal')?.remove()}
  function highlight(el){if(!el)return;el.classList.remove('guide-highlight');void el.offsetWidth;el.classList.add('guide-highlight');el.scrollIntoView({behavior:'smooth',block:'center'})}
  function openModal(){closeModal();document.body.insertAdjacentHTML('beforeend',modalHtml());const root=document.querySelector('#learningGuideModal');root.querySelector('#learningGuideClose').onclick=closeModal;root.addEventListener('click',e=>{if(e.target===root)closeModal()});root.querySelector('#guideGoRoadmap').onclick=()=>{closeModal();try{if(typeof go==='function')go('home')}catch{};setTimeout(()=>{const r=document.querySelector('#learningRoadmap');highlight(r);const first=r?.querySelector(`[data-path-level="${route().start}"]`);if(first)first.focus({preventScroll:true})},120)};root.querySelector('#guideGoCore').onclick=()=>{closeModal();setTimeout(()=>{if(window.openCore3000Study)window.openCore3000Study();else highlight(document.querySelector('#core3000Plan'))},80)};root.querySelector('#guideGoReview').onclick=()=>{closeModal();try{go('review')}catch{}};root.querySelector('#guideGoSentence').onclick=()=>{closeModal();window.openSentenceCoach?.()}}
  function renderCard(){if(typeof view!=='undefined'&&view!=='home')return;const app=document.querySelector('#app');if(!app)return;document.querySelector('#learningGuideCard')?.remove();const hero=app.querySelector('.hero');if(!hero)return;hero.insertAdjacentHTML('afterend',cardHtml());document.querySelector('#learningGuideOpen')?.addEventListener('click',openModal)}
  window.openLearningGuide=openModal;window.addEventListener('DOMContentLoaded',()=>requestAnimationFrame(renderCard));document.addEventListener('learner-level:changed',()=>setTimeout(renderCard,0));const observer=new MutationObserver(()=>{if(typeof view!=='undefined'&&view==='home'&&!document.querySelector('#learningGuideCard'))requestAnimationFrame(renderCard)});observer.observe(document.querySelector('#app')||document.body,{childList:true,subtree:true});
})();