(()=>{
  const special={the:'เดอะ',of:'ออฟ',and:'แอนด์',to:'ทู',a:'อะ',an:'แอน',in:'อิน',for:'ฟอร์',is:'อิซ',on:'ออน',that:'แดต',by:'บาย',this:'ดิส',with:'วิธ',i:'ไอ',you:'ยู',it:'อิท',not:'น็อต',or:'ออร์',be:'บี',are:'อาร์',from:'ฟรอม',at:'แอท',as:'แอซ',your:'ยัวร์',all:'ออล',have:'แฮฟ',new:'นิว',more:'มอร์',was:'วอซ',we:'วี',will:'วิล',home:'โฮม',can:'แคน',us:'อัส',about:'อะเบาท์',if:'อิฟ',my:'มาย',has:'แฮซ',but:'บัท',our:'อาวร์',one:'วัน',other:'อัธเธอร์',do:'ดู',no:'โน',information:'อินฟอร์เมชัน',time:'ไทม์',they:'เดย์',he:'ฮี',up:'อัพ',may:'เมย์',what:'ว็อท',which:'วิช',their:'แดร์',out:'เอาท์',use:'ยูซ',any:'เอนี',there:'แดร์',see:'ซี',only:'โอนลี',so:'โซ',his:'ฮิซ',when:'เว็น',here:'เฮียร์',who:'ฮู',also:'ออลโซ',now:'นาว',help:'เฮลป์',get:'เก็ต',go:'โก',make:'เมค',like:'ไลก์',work:'เวิร์ก',people:'พีเพิล',good:'กูด',know:'โน',think:'ธิงก์',take:'เทค',come:'คัม',want:'วอนท์',look:'ลุค',first:'เฟิร์สต์',day:'เดย์',way:'เวย์',find:'ไฟนด์',give:'กิฟ',many:'เมนี',well:'เวล',back:'แบ็ก',very:'เวรี',after:'แอฟเทอร์',even:'อีเวิน',because:'บีคอส',these:'ดีซ',most:'โมสต์',where:'แวร์',much:'มัช',before:'บีฟอร์',right:'ไรต์',too:'ทู',mean:'มีน',old:'โอลด์',same:'เซม',tell:'เทล',boy:'บอย',girl:'เกิร์ล',man:'แมน',woman:'วูแมน',water:'วอเทอร์',food:'ฟูด',book:'บุ๊ก',phone:'โฟน',school:'สกูล',friend:'เฟรนด์',family:'แฟมิลี',name:'เนม',hello:'เฮลโล',please:'พลีซ',thank:'แธงก์',thanks:'แธงก์ส',sorry:'ซอรี',yes:'เยส'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function rows(){return (window.OXFORD3000_RAW||[]).map(r=>({id:r[0],word:r[1],part:r[2],level:r[3],thai:r[4],example:r[5],exampleThai:r[6]||''}))}
  function speechText(word){return String(word||'').replace(/\s*\([^)]*\)\s*/g,' ').replace(/\s+/g,' ').trim()}
  function reading(word){
    const raw=speechText(word),first=raw.split(/[,/;]/)[0].trim(),w=first.toLowerCase();if(special[w])return special[w];
    let s=w;const rules=[[/tion$/g,'ชัน'],[/sion$/g,'ชัน'],[/ture$/g,'เชอร์'],[/ough$/g,'อัฟ'],[/eigh/g,'เอ'],[/igh/g,'ไอ'],[/ph/g,'ฟ'],[/sh/g,'ช'],[/ch/g,'ช'],[/th/g,'ธ'],[/wh/g,'ว'],[/ck/g,'ค'],[/ng/g,'ง'],[/qu/g,'คว'],[/ee/g,'อี'],[/ea/g,'อี'],[/oo/g,'อู'],[/ai/g,'เอ'],[/ay/g,'เอ'],[/oa/g,'โอ'],[/ow/g,'เอา'],[/ou/g,'เอา'],[/oi/g,'ออย'],[/oy/g,'ออย'],[/ar/g,'อาร์'],[/er/g,'เออร์'],[/ir/g,'เออร์'],[/ur/g,'เออร์'],[/or/g,'ออร์']];
    for(const [a,b] of rules)s=s.replace(a,b);const map={a:'แอ',b:'บ',c:'ค',d:'ด',e:'เอ',f:'ฟ',g:'ก',h:'ฮ',i:'อิ',j:'จ',k:'ค',l:'ล',m:'ม',n:'น',o:'ออ',p:'พ',q:'ค',r:'ร',s:'ส',t:'ท',u:'อั',v:'ว',w:'ว',x:'กซ',y:'ย',z:'ซ'};
    return s.replace(/[a-z]/g,ch=>map[ch]||ch).replace(/เอ$/,'').replace(/([ก-ฮ])\1+/g,'$1')||first;
  }
  function speakWord(word){const text=speechText(word);try{if(typeof speak==='function'){speak(text);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.86;speechSynthesis.speak(u)}catch{}}
  function shuffle(arr,seed){const a=[...arr];let x=Number.isFinite(seed)?seed:(Date.now()^Math.floor(Math.random()*0x7fffffff));const rnd=()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296};for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function highlight(entry){const example=String(entry?.example||''),word=String(entry?.word||''),target=speechText(word).split(/[,/;]/)[0].trim();if(!example)return `<u class="story-vocab">${esc(word)}</u>`;const safe=target.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const re=new RegExp(`\\b(${safe})\\b`,'i');if(re.test(example))return esc(example).replace(re,m=>`<u class="story-vocab" data-say="${esc(target)}">${m}</u>`);return `<u class="story-vocab" data-say="${esc(target)}">${esc(word)}</u> — ${esc(example)}`}
  window.getOxford3000=rows;window.oxfordEsc=esc;window.oxfordSpeechText=speechText;window.oxfordThaiReading=reading;window.oxfordSpeak=speakWord;window.oxfordShuffle=shuffle;window.oxfordHighlightExample=highlight;
})();
