const SCENARIOS={daily:'daily life and friendly small talk',coffee:'ordering at a cafe',travel:'travel and transportation',work:'simple workplace conversation',restaurant:'ordering and paying at a restaurant',shopping:'shopping, price, size and payment',hotel:'hotel check-in and room needs',airport:'airport check-in, gates and baggage'};
const MODELS=[{id:'qwen/qwen3.6-27b',label:'Qwen 3.6 27B'},{id:'openai/gpt-oss-20b',label:'GPT-OSS 20B'}];
const BAD=/^(english coach reply|short thai coaching note|coach reply|thai coaching note|example reply|response)$/i;
function strip(v){return String(v||'').replace(/<think>[\s\S]*?<\/think>/gi,' ').replace(/<\/?think>/gi,' ').replace(/^```json\s*/i,'').replace(/\s*```$/,'').trim()}
function history(v){return Array.isArray(v)?v.slice(-8).map(x=>({role:x?.role==='user'?'user':'assistant',content:String(x?.text||'').slice(0,500)})).filter(x=>x.content):[]}
function parse(raw){const clean=strip(raw);let val=null;try{const a=clean.indexOf('{'),b=clean.lastIndexOf('}');val=JSON.parse(a>=0&&b>a?clean.slice(a,b+1):clean)}catch{};const text=strip(val?.text||'').slice(0,700),thai=strip(val?.thai||'').slice(0,500),corrected=strip(val?.corrected||'').slice(0,400);if(!text||BAD.test(text)||BAD.test(thai)||text.length<4)throw new Error('bad_coach_payload');return{text,thai,corrected}}
function local(message){const t=String(message||'').trim(),l=t.toLowerCase();if(/not good (in|at) english|teach me( the)? english/.test(l))return{text:'Of course. Let’s start with one easy sentence: “I am learning English.” Can you say that?',thai:'ได้เลย เริ่มจากประโยคง่าย ๆ ก่อน: I am learning English. = ฉันกำลังเรียนภาษาอังกฤษ',corrected:"I'm not very good at English. Please teach me."};if(/listen|speak|pronunciation/.test(l))return{text:'Sure. Listen and repeat: “I am learning English every day.” Can you say it slowly?',thai:'กดปุ่มฟังคำตอบ แล้วพูดตามช้า ๆ: I am learning English every day.',corrected:'I want to listen. Can you speak slowly?'};if(/i.?m working today and so tired/.test(l))return{text:'Good try. A natural sentence is: “I worked today, so I’m very tired.” What made work tiring today?',thai:'ถ้าหมายถึงทำงานมาแล้ววันนี้ ใช้ I worked today, so I’m very tired. จะเป็นธรรมชาติกว่า',corrected:"I worked today, so I'm very tired."};return{text:'Good try. I’ll help you improve it. Can you tell me the same idea in one short sentence?',thai:'ลองพูดใจความเดิมเป็นประโยคสั้น ๆ หนึ่งประโยค แล้วฉันจะช่วยแก้ให้',corrected:''}}
async function call(model,messages,system){const key=process.env.GROQ_API_KEY;if(!key)throw new Error('missing_key');const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:model.id,messages:[{role:'system',content:system},...messages],temperature:.2,max_completion_tokens:260,stream:false})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error('groq_'+r.status);return{...parse(d?.choices?.[0]?.message?.content||''),model:model.id,modelLabel:model.label,source:'groq-free-plan',freeOnly:true}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method==='OPTIONS'){res.status(204).end();return}if(req.method==='GET'){res.status(200).json({ok:true,version:'coach-v2',provider:'groq-free-plan'});return}if(req.method!=='POST'){res.status(405).json({error:'method_not_allowed'});return}const body=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),message=String(body.message||'').trim().slice(0,800);if(!message){res.status(400).json({error:'message_required'});return}const learner=String(body.name||'ผู้เรียน').slice(0,30),scenario=SCENARIOS[body.scenario]||SCENARIOS.daily;const messages=[...history(body.history),{role:'user',content:message}];const recent=(Array.isArray(body.history)?body.history:[]).filter(x=>x?.role==='ai').slice(-3).map(x=>String(x.text||'')).join(' | ');const system=`You are a patient English TEACHER for a Thai beginner named ${learner}. Context: ${scenario}.
First understand what the learner actually wants. If they ask to be taught, teach them. If they ask to listen/speak/practice pronunciation, give one short sentence for listening and repetition. If their English is unnatural or incorrect, provide a corrected natural sentence.
Reply in simple English, maximum 3 short sentences. Give a concise Thai teaching note. End with exactly ONE easy question or speaking task. Do not repeat recent assistant replies: ${recent||'none'}.
Never output placeholders, labels, template text, markdown, analysis, or reasoning. Do NOT write phrases such as English coach reply, short Thai coaching note, or example response.
Return ONLY JSON with real content using keys text, thai, corrected. corrected may be empty if no correction is needed.`;for(const model of MODELS){try{const out=await call(model,messages,system);if(recent&&recent.includes(out.text))throw new Error('repeat');res.status(200).json(out);return}catch{}}const out=local(message);res.status(200).json({...out,source:'local-teacher-v2',freeOnly:true})}