import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const source=fs.readFileSync('fun-lessons-v69.js','utf8');
const css=fs.readFileSync('fun-lessons-v69.css','utf8');
const store=new Map(); class Element{}
const kinds=['intro','present','continuous','past','future','there','can','modal','quantity','wouldlike','wh','opinion','sequence','health','work'];
const dataFor=day=>{
  const kind=kinds[(day-1)%kinds.length];
  const vocab=Array.from({length:6},(_,i)=>({en:`word${day}_${i}`,th:`คำ${day}_${i}`,part:'n.'}));
  const examplePairs=Array.from({length:8},(_,i)=>({en:`Teaching example lesson ${day} number ${i+1}.`,th:`ตัวอย่างสอนบท ${day} ลำดับ ${i+1}`}));
  const quiz=Array.from({length:8},(_,i)=>({t:'mc',p:`คำถามใหม่บท ${day} ข้อ ${i+1}`,c:`answer${day}_${i}`,o:[`answer${day}_${i}`,`wrong${day}_${i}_1`,`wrong${day}_${i}_2`,`wrong${day}_${i}_3`],ans:`answer${day}_${i}`}));
  return {lesson:{day,cefr:'A1',title:`หัวข้อบท ${day}`,goal:`เป้าหมายภาษาไทยบท ${day}`,scenario:`สถานการณ์บท ${day}`,focusWord:vocab[0],vocab,examplePairs},grammar:{name:`Grammar ${day}`,formula:`Subject + pattern ${day}`,th:`อธิบายแกรมม่าเป็นภาษาไทยสำหรับบท ${day}`,tip:`จำวิธีใช้บท ${day}`,kind},quiz};
};
const document={querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},body:{appendChild(){}},createElement(){return{innerHTML:'',querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},remove(){},setAttribute(){},appendChild(){},classList:{add(){},toggle(){}}}}};
const sandbox={console,document,Element,Event:class{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},getLearnerLevel:()=> 'starter',getDailyCourseProgress:()=>({currentDay:1,unlockedThrough:210,completed:[],startDay:1}),getFunLessonDataV68:dataFor,addEventListener(){},setTimeout(fn){if(typeof fn==='function')fn();return 0},clearTimeout(){},speechSynthesis:{cancel(){},speak(){},getVoices(){return[]}},SpeechSynthesisUtterance:class{},navigator:{}};
sandbox.window=sandbox;
vm.createContext(sandbox);
vm.runInContext(source,sandbox,{filename:'fun-lessons-v69.js'});
const audit=sandbox.auditFunLessonsV69();
assert.equal(audit.version,'v69');
assert.equal(audit.totalLessons,210);
assert.equal(audit.totalTeachingStages,1260);
assert.equal(audit.cartoonLessons,210);
assert.equal(audit.thaiTeacherLessons,210);
assert.equal(audit.cartoonsPerLesson,3);
assert.equal(audit.inlineSvgCartoons,true);
assert.equal(audit.animatedCartoons,true);
assert.equal(audit.thaiNarration,true);
assert.equal(audit.teachBeforeTest,true);
assert.equal(audit.grammarBeforeQuiz,true);
assert.equal(audit.fourSkillsBeforeQuiz,true);
assert.equal(audit.quizQuestions,8);
assert.equal(audit.quizPass,6);
assert.equal(audit.quizBad.length,0);
assert.equal(audit.teachingQuizExactLeaks.length,0);
assert.equal(audit.databaseMediaStorage,false);
assert.equal(audit.ok,true);
assert(source.includes("u.lang=lang"),'Narration language selection missing');
assert(source.includes("sayTh(t)=>")===false);
assert(source.includes("const sayTh=t=>speak(t,'th-TH')"),'Thai narration missing');
assert(source.includes('aria-label="ครูการ์ตูน"'),'Teacher SVG missing');
assert(source.includes('aria-label="นักเรียนการ์ตูน"'),'Student SVG missing');
assert(source.includes('ครูเมย์'),'Thai teacher character missing');
assert(source.includes('ก่อนสอบ'),'Teach-before-test copy missing');
assert(css.includes('@keyframes v69bob'),'Cartoon animation missing');
assert(css.includes('@keyframes v69blink'),'Cartoon blink animation missing');
assert(css.includes('.v69-dialogue-scene'),'Cartoon dialogue styling missing');
console.log(JSON.stringify({ok:true,version:'v69',lessons:210,teachingStages:1260,cartoonLessons:210,cartoonsPerLesson:3,thaiTeacher:true,grammarBeforeQuiz:true,fourSkillsBeforeQuiz:true,quiz:'6/8',databaseMediaStorage:false},null,2));
