import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync('fun-lessons-v66.js','utf8');
const store=new Map();class Element{}
const fakeLesson=day=>({day,cefr:day<57?'A1':day<99?'A1–A2':day<141?'A2–B1':'B1–B2',title:`Lesson ${day}`,goal:`Goal ${day}`,scenario:`Scenario ${day}`,focusWord:{en:`focus${day}`,th:`คำ${day}`},vocab:Array.from({length:6},(_,i)=>({en:`word${day}_${i}`,th:`ศัพท์${day}_${i}`})),examplePairs:Array.from({length:4},(_,i)=>({en:`This is unique sentence ${day} number ${i+1}.`,th:`ประโยคเฉพาะ ${day} หมายเลข ${i+1}`,word:`word${day}_${i}`,wordThai:`ศัพท์${day}_${i}`})),examples:[]});
const document={querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},dispatchEvent(){},body:{appendChild(){}}};
const sandbox={console,document,Element,Event:class{},CustomEvent:class{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},getLearnerLevel:()=> 'intermediate',getDailyCourseProgress:()=>({currentDay:71,unlockedThrough:210,completed:[],startDay:1}),getDailyLesson:fakeLesson,addEventListener(){},setTimeout(){return 0},speechSynthesis:{cancel(){},speak(){}},SpeechSynthesisUtterance:class{}};sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(source,sandbox,{filename:'fun-lessons-v66.js'});
const audit=sandbox.auditFunLessonsV66();
assert.equal(audit.totalLessons,210);assert.equal(audit.distinctLessonMethods,210,'Every lesson must have a unique play-method sequence');assert.equal(audit.duplicateMethodSequences.length,0);assert.equal(audit.targetSentenceRepeats.length,0);assert.equal(audit.decoyLeaks.length,0);assert.equal(audit.missionCount,4);assert(audit.methodsUsed>=20);assert(audit.minMinutes>=10);assert(audit.maxMinutes<=15);assert.equal(audit.micOrTyping,true);assert.equal(audit.noSixPhaseUi,true);assert.equal(audit.ok,true);
const signatures=new Set();for(let day=1;day<=210;day++){const b=sandbox.buildFunLessonBlueprintV66(day),d=sandbox.getFunLessonDataV66(day);assert(b.targetMinutes>=10&&b.targetMinutes<=15,`Lesson ${day} duration invalid`);assert.equal(b.methods.length,4);assert(!signatures.has(b.signature),`Lesson ${day} repeats method sequence`);signatures.add(b.signature);assert.equal(new Set(d.pairs.map(p=>p.en)).size,4,`Lesson ${day} repeats target sentence inside lesson`);const cur=new Set(fakeLesson(day).examplePairs.flatMap(p=>[p.en,p.th]));assert(d.decoyPairs.every(p=>!cur.has(p.en)&&!cur.has(p.th)),`Lesson ${day} leaks current answers into decoys`)}
const index=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');assert(index.includes('fun-lessons-v66.css?v=66'));assert(index.includes('fun-lessons-v66.js?v=66'));assert(index.indexOf('fun-lessons-v66.js?v=66')<index.indexOf('institute-course-v62.js?v=62'),'v66 must register its click capture before v62');assert(sw.includes("const CACHE='my-english-v65'"));assert(sw.includes('./fun-lessons-v66.css?v=66')&&sw.includes('./fun-lessons-v66.js?v=66'));assert(!source.includes('MutationObserver'));console.log(JSON.stringify({ok:true,version:'v66',lessons:210,uniqueMethodSequences:audit.distinctLessonMethods,minutes:[audit.minMinutes,audit.maxMinutes],missionsPerLesson:audit.missionCount,methodsUsed:audit.methodsUsed,micOrTyping:audit.micOrTyping,noSixPhaseUi:audit.noSixPhaseUi},null,2));
