import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync('fun-lessons-v70.js','utf8'),css=fs.readFileSync('fun-lessons-v70.css','utf8');
const store=new Map();class Element{}
const kinds=['intro','present','continuous','past','future','there','can','modal','quantity','wouldlike','wh','opinion','sequence','health','work'];
const dataFor=day=>{let kind=kinds[(day-1)%kinds.length],vocab=Array.from({length:6},(_,i)=>({en:`word${day}_${i}`,th:`คำ${day}_${i}`,part:'n.'})),examplePairs=Array.from({length:8},(_,i)=>({en:`Example lesson ${day} number ${i+1}.`,th:`ตัวอย่างบท ${day} ลำดับ ${i+1}`})),quiz=Array.from({length:8},(_,i)=>({p:`โจทย์ภาษาไทย ${day}-${i}`,c:`answer${day}_${i}`,o:[`answer${day}_${i}`,`wrong${day}_${i}_1`,`wrong${day}_${i}_2`,`wrong${day}_${i}_3`],ans:`answer${day}_${i}`}));return{lesson:{cefr:'A1',title:`English title ${day}`,goal:`English goal ${day}`,scenario:`English scenario ${day}`,focusWord:vocab[0],vocab,examplePairs},grammar:{kind,formula:`Subject + pattern ${day}`,name:`English Grammar ${day}`},quiz}};
const document={querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},body:{appendChild(){}},createElement(){return{innerHTML:'',querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},remove(){},setAttribute(){},appendChild(){},classList:{add(){},toggle(){}}}}};
const sandbox={console,document,Element,Event:class{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},getLearnerLevel:()=> 'starter',getDailyCourseProgress:()=>({currentDay:1,unlockedThrough:210,completed:[],startDay:1}),getFunLessonDataV68:dataFor,addEventListener(){},setTimeout(fn){if(typeof fn==='function')fn();return 0},clearTimeout(){},speechSynthesis:{cancel(){},speak(){},getVoices(){return[]}},SpeechSynthesisUtterance:class{},navigator:{}};sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(source,sandbox,{filename:'fun-lessons-v70.js'});
const a=sandbox.auditFunLessonsV70();
assert.equal(a.version,'v70');assert.equal(a.totalLessons,210);assert.equal(a.totalTeachingStages,1260);assert.equal(a.thaiFirstLessons,210);assert.equal(a.redesignedCartoonLessons,210);assert.equal(a.thaiInstruction,true);assert.equal(a.thaiFeedback,true);assert.equal(a.thaiButtons,true);assert.equal(a.englishRole,'learning-content-only');assert.equal(a.grammarBeforeQuiz,true);assert.equal(a.teachBeforeTest,true);assert.equal(a.quizQuestions,8);assert.equal(a.quizPass,6);assert.equal(a.databaseMediaStorage,false);assert.equal(a.ok,true);
assert(source.includes("const V='v70'"));assert(source.includes("const sayTh=t=>speak(t,'th-TH')"));assert(source.includes('ครูเมย์'));assert(source.includes('มิน'));assert(source.includes('นนท์'));assert(source.includes('ภาษาไทย'));assert(source.includes('englishRole:\'learning-content-only\''));assert(source.includes('databaseMediaStorage:false'));assert(!source.includes('MutationObserver'));
assert(css.includes('@keyframes v70Float'));assert(css.includes('@keyframes v70Point'));assert(css.includes('@keyframes v70Blink'));assert(css.includes('.v70-teacher'));assert(css.includes('.v70-dialogue'));assert(css.includes('prefers-reduced-motion'));
console.log(JSON.stringify({ok:true,version:'v70',lessons:210,teachingStages:1260,thaiFirst:true,cartoonRedesign:true,teacher:'ครูเมย์',students:['มิน','นนท์'],quiz:'6/8',databaseMediaStorage:false},null,2));