import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const root=path.resolve(process.cwd());
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const packs=['oxford3000-pack-01.js','oxford3000-pack-02.js','oxford3000-pack-03.js','oxford3000-pack-03b.js','oxford3000-pack-04.js','oxford3000-pack-05.js','oxford3000-pack-06.js','oxford3000-pack-07.js','oxford3000-pack-08.js'];
let b64='';for(const name of packs){const m=read(name).match(/\+\s*'([A-Za-z0-9+/=]+)'\s*;?\s*$/);assert(m,`Cannot extract ${name}`);b64+=m[1]}
const parsed=JSON.parse(zlib.gunzipSync(Buffer.from(b64,'base64')).toString('utf8'));
const raw=Array.isArray(parsed)?parsed:(parsed.rows||parsed.data||parsed.words||parsed.items||[]);
const rows=raw.map((r,i)=>Array.isArray(r)?{id:r[0]??i+1,word:r[1],part:r[2],level:r[3],thai:r[4],example:r[5],exampleThai:r[6]||''}:r);
assert.equal(rows.length,3000);

const store=new Map();class Element{}
const document={documentElement:{classList:{contains:()=>false}},body:{contains:()=>false,appendChild(){}},head:{appendChild(){}},addEventListener(){},dispatchEvent(){},querySelector(){return null},querySelectorAll(){return[]},createElement(){return {textContent:'',style:{},appendChild(){},querySelector(){return null},querySelectorAll(){return[]},setAttribute(){},insertAdjacentElement(){},addEventListener(){},remove(){}}},createTextNode(text){return{textContent:text}}};
const sandbox={console,document,Element,Event:class{},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init?.detail}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},getLearnerLevel:()=> 'intermediate',getLearnerLevelInfo:()=>({label:'กลาง',cefr:'A2–B1',cefrLevels:['A2','B1']}),getOxford3000:()=>rows,ensureOxford3000:async()=>rows,getDailyCourseProgress:()=>({currentDay:71,unlockedThrough:71,completed:[],startDay:71}),addEventListener(){},setTimeout(fn){if(typeof fn==='function')fn();return 0},clearTimeout(){},setInterval(){return 1},clearInterval(){},requestAnimationFrame(fn){if(typeof fn==='function')fn();return 0},speechSynthesis:{cancel(){},speak(){}},SpeechSynthesisUtterance:class{}};
sandbox.window=sandbox;vm.createContext(sandbox);
vm.runInContext(read('daily-course-v53.js'),sandbox,{filename:'daily-course-v53.js'});
vm.runInContext(read('curriculum-quality-v57.js'),sandbox,{filename:'curriculum-quality-v57.js'});
vm.runInContext(read('course-game-fixes-v59.js'),sandbox,{filename:'course-game-fixes-v59.js'});
vm.runInContext(read('curriculum-variety-v60.js'),sandbox,{filename:'curriculum-variety-v60.js'});
await Promise.resolve();await Promise.resolve();await new Promise(r=>setImmediate(r));
vm.runInContext(read('lesson-variety-v64.js'),sandbox,{filename:'lesson-variety-v64.js'});
vm.runInContext(read('mastery-variety-v64b.js'),sandbox,{filename:'mastery-variety-v64b.js'});
vm.runInContext(read('interaction-quality-v65.js'),sandbox,{filename:'interaction-quality-v65.js'});

const audit=sandbox.auditInteractionQualityV65();
assert.equal(audit.totalLessons,210);assert.equal(audit.incomplete.length,0);assert.equal(audit.reservedLeaks.length,0);assert.equal(audit.duplicateAnswers.length,0);assert.equal(audit.duplicateConcepts.length,0);assert.equal(audit.badOptions.length,0);assert(audit.typesUsed>=5);assert.equal(audit.gameMinutes.min,10);assert.equal(audit.gameMinutes.max,20);assert.equal(audit.gameMinutes.first,10);assert.equal(audit.gameMinutes.last,20);assert.equal(audit.gameMinutes.nondecreasing,true);assert.equal(audit.micOrTyping,true);assert.equal(audit.ok,true);
for(let day=1;day<=210;day++){const count=[21,56,98,140,182,210].includes(day)?15:day%7===0?10:5,items=sandbox.buildSeparatedMasteryV65(day,count,0),lesson=sandbox.getDailyLesson(day),reservedEn=new Set((lesson.examplePairs||[]).map(p=>String(p.en||'').toLowerCase().replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim())),reservedRaw=new Set((lesson.examplePairs||[]).flatMap(p=>[String(p.en||'').trim(),String(p.th||'').trim()]));assert.equal(items.length,count);assert.equal(new Set(items.map(x=>x.conceptKey)).size,items.length);for(const item of items){const c=String(item.conceptKey||'');if(c.startsWith('pair:'))assert(!reservedEn.has(c.slice(5)));assert(item.options.every(o=>!reservedRaw.has(String(o.label||'').trim())));assert.equal(item.options.filter(o=>o.correct).length,1)}const minutes=sandbox.getGameSessionMinutesV65(day);assert(minutes>=10&&minutes<=20)}
const source=read('interaction-quality-v65.js'),index=read('index.html'),sw=read('sw.js');assert(source.includes("const VERSION='v65'"));assert(source.includes('buildSeparatedMasteryV65'));assert(source.includes('SpeechRecognition')&&source.includes('พูดเพื่อตอบ'));assert(source.includes('.v62-text-input, .v62-textarea'));assert(source.includes('gameMinutesForDay')&&source.includes('10+')&&source.includes('*60000'));assert(!source.includes('MutationObserver'));assert(index.includes('interaction-quality-v65.css?v=65'));assert(index.includes('interaction-quality-v65.js?v=65'));assert(index.indexOf('interaction-quality-v65.js?v=65')>index.indexOf('mastery-variety-v64b.js?v=64'));assert(index.includes('fun-lessons-v68.js?v=68'));assert(index.includes('fun-lessons-v69.js?v=69'));assert(index.includes('fun-lessons-v70.js?v=70'));assert(index.includes('fun-lessons-v71.js?v=71'));assert(sw.includes("const CACHE='my-english-v71'"));assert(sw.includes('./interaction-quality-v65.css?v=65')&&sw.includes('./interaction-quality-v65.js?v=65'));assert(sw.includes('./fun-lessons-v68.js?v=68')&&sw.includes('./fun-lessons-v68.css?v=68'));assert(sw.includes('./fun-lessons-v69.js?v=69')&&sw.includes('./fun-lessons-v69.css?v=69'));assert(sw.includes('./fun-lessons-v70.js?v=70')&&sw.includes('./fun-lessons-v70.css?v=70'));assert(sw.includes('./fun-lessons-v71.js?v=71')&&sw.includes('./fun-lessons-v71.css?v=71'));
const lesson22=sandbox.getDailyLesson(22),items22=sandbox.buildSeparatedMasteryV65(22,5,0),lesson22Pairs=new Set((lesson22.examplePairs||[]).map(p=>String(p.en||'').toLowerCase().replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim()));assert(items22.every(x=>!String(x.conceptKey||'').startsWith('pair:')||!lesson22Pairs.has(String(x.conceptKey).slice(5))));console.log(JSON.stringify({ok:true,version:'v65',mastery:{questions:audit.masteryQuestions,typesUsed:audit.typesUsed,reservedLeaks:audit.reservedLeaks.length,duplicateAnswers:audit.duplicateAnswers.length,duplicateConcepts:audit.duplicateConcepts.length,badOptions:audit.badOptions.length},games:audit.gameMinutes,micOrTyping:audit.micOrTyping,lesson22Separated:true,compatibleWith:'v71'},null,2));