import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const root=path.resolve(process.cwd());
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const packs=['oxford3000-pack-01.js','oxford3000-pack-02.js','oxford3000-pack-03.js','oxford3000-pack-03b.js','oxford3000-pack-04.js','oxford3000-pack-05.js','oxford3000-pack-06.js','oxford3000-pack-07.js','oxford3000-pack-08.js'];
let b64='';for(const name of packs){const m=read(name).match(/\+\s*'([A-Za-z0-9+/=]+)'\s*;?\s*$/);assert(m,`Cannot extract ${name}`);b64+=m[1]}
const parsed=JSON.parse(zlib.gunzipSync(Buffer.from(b64,'base64')).toString('utf8'));
const raw=Array.isArray(parsed)?parsed:(parsed.rows||parsed.data||parsed.words||parsed.items||[]);
const rows=raw.map((r,i)=>Array.isArray(r)?{id:r[0]??i+1,word:r[1],part:r[2],level:r[3],thai:r[4],example:r[5],exampleThai:r[6]||''}:r);
assert.equal(rows.length,3000);
const store=new Map();class Element{}
const document={documentElement:{classList:{contains:()=>false}},body:{contains:()=>false,appendChild(){}},head:{appendChild(){}},addEventListener(){},dispatchEvent(){},querySelector(){return null},querySelectorAll(){return[]},createElement(){return {textContent:'',innerHTML:'',style:{},appendChild(){},querySelector(){return null},querySelectorAll(){return[]},setAttribute(){},insertAdjacentElement(){},addEventListener(){},remove(){},classList:{add(){},toggle(){}}}},createTextNode(text){return{textContent:text}}};
const levelInfo={label:'กลาง',cefr:'A2–B1',cefrLevels:['A2','B1']};
const sandbox={console,document,Element,Event:class{},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init?.detail}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},getLearnerLevel:()=> 'intermediate',getLearnerLevelInfo:()=>levelInfo,getOxford3000:()=>rows,ensureOxford3000:async()=>rows,getDailyCourseProgress:()=>({currentDay:71,unlockedThrough:210,completed:[],startDay:71}),addEventListener(){},setTimeout(fn){if(typeof fn==='function')fn();return 0},clearTimeout(){},requestAnimationFrame(fn){if(typeof fn==='function')fn();return 0},speechSynthesis:{cancel(){},speak(){},getVoices(){return[]}},SpeechSynthesisUtterance:class{},navigator:{}};
sandbox.window=sandbox;vm.createContext(sandbox);
for(const f of ['daily-course-v53.js','curriculum-quality-v57.js','course-game-fixes-v59.js','curriculum-variety-v60.js'])vm.runInContext(read(f),sandbox,{filename:f});await Promise.resolve();await Promise.resolve();await new Promise(r=>setImmediate(r));vm.runInContext(read('fun-lessons-v68.js'),sandbox,{filename:'fun-lessons-v68.js'});await Promise.resolve();await Promise.resolve();await new Promise(r=>setImmediate(r));vm.runInContext(read('fun-lessons-v69.js'),sandbox,{filename:'fun-lessons-v69.js'});await Promise.resolve();await new Promise(r=>setImmediate(r));
const audit=sandbox.auditFunLessonsV69();assert.equal(audit.version,'v69');assert.equal(audit.totalLessons,210);assert.equal(audit.totalTeachingStages,1260);assert.equal(audit.cartoonLessons,210);assert.equal(audit.thaiTeacherLessons,210);assert.equal(audit.cartoonsPerLesson,3);assert.equal(audit.inlineSvgCartoons,true);assert.equal(audit.animatedCartoons,true);assert.equal(audit.thaiNarration,true);assert.equal(audit.teachBeforeTest,true);assert.equal(audit.grammarBeforeQuiz,true);assert.equal(audit.fourSkillsBeforeQuiz,true);assert.equal(audit.quizQuestions,8);assert.equal(audit.quizPass,6);assert.equal(audit.quizBad.length,0);assert.equal(audit.teachingQuizExactLeaks.length,0);assert.equal(audit.databaseMediaStorage,false);assert.equal(audit.ok,true);
for(let day=1;day<=210;day++){const data=sandbox.getFunLessonDataV68(day);assert.equal(data.lesson.vocab.length,6);assert.equal(data.lesson.examplePairs.length,8);assert.equal(data.quiz.length,8);const bp=await sandbox.buildFunLessonBlueprintV69(day);assert.deepEqual(Array.from(bp.stages,x=>x.code),['intro','words','grammar','dialogue','skills','practice']);assert.equal(bp.cartoons.length,3);assert.equal(bp.thaiInstruction,true);assert.equal(bp.teacherNarration,true)}
const source=read('fun-lessons-v69.js'),css=read('fun-lessons-v69.css'),index=read('index.html'),sw=read('sw.js');assert(source.includes("const V='v69'"));assert(source.includes("const sayTh=t=>speak(t,'th-TH')"));assert(source.includes('ครูเมย์'));assert(source.includes('databaseMediaStorage:false'));assert(!source.includes('MutationObserver'));assert(css.includes('@keyframes v69bob'));assert(!index.includes('fun-lessons-v69.js?v=69'));assert(index.includes('fun-lessons-v68.js?v=68'));assert(index.includes('curriculum-v72.js?v=72'));assert(index.includes('core-vocab-v73.js?v=73'));assert(index.includes('curriculum-institute-v73.js?v=73'));assert(index.includes('lesson-experience-v72.js?v=72e'));assert(sw.includes("const CACHE='my-english-v73-institute1'"));assert(!sw.includes('./fun-lessons-v69.js?v=69'));assert(sw.includes('./fun-lessons-v68.js?v=68'));assert(sw.includes('./core-vocab-v73.js?v=73'));assert(sw.includes('./curriculum-institute-v73.js?v=73'));assert(sw.includes('./lesson-experience-v72.js?v=72e'));console.log(JSON.stringify({ok:true,version:'v69',realCurriculum:true,lessons:210,rollbackFileRetained:true,productionLoaded:false,compatibleWith:'v73-institute1'},null,2));